# Site setting

Title: New Project
Username: FrancesFagan
desciption to be rendered in footer: >
Angle bracket allows for lenthier description in footer

#Build settings
Markdown settings to be used:kramdown
More infor here
